// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.11.4
// source: OrderHandler.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OrderCreatedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderCreatedRequest) Reset() {
	*x = OrderCreatedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedRequest) ProtoMessage() {}

func (x *OrderCreatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedRequest.ProtoReflect.Descriptor instead.
func (*OrderCreatedRequest) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{0}
}

type OrderCreatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: json:"code" form:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//@inject_tag: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" form:"msg"`
}

func (x *OrderCreatedResponse) Reset() {
	*x = OrderCreatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreatedResponse) ProtoMessage() {}

func (x *OrderCreatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreatedResponse.ProtoReflect.Descriptor instead.
func (*OrderCreatedResponse) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{1}
}

func (x *OrderCreatedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderCreatedResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderUpdatedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderUpdatedRequest) Reset() {
	*x = OrderUpdatedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdatedRequest) ProtoMessage() {}

func (x *OrderUpdatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdatedRequest.ProtoReflect.Descriptor instead.
func (*OrderUpdatedRequest) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{2}
}

type OrderUpdatedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: json:"code" form:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//@inject_tag: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" form:"msg"`
}

func (x *OrderUpdatedResponse) Reset() {
	*x = OrderUpdatedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderUpdatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdatedResponse) ProtoMessage() {}

func (x *OrderUpdatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdatedResponse.ProtoReflect.Descriptor instead.
func (*OrderUpdatedResponse) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{3}
}

func (x *OrderUpdatedResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderUpdatedResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type OrderFindRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderFindRequest) Reset() {
	*x = OrderFindRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFindRequest) ProtoMessage() {}

func (x *OrderFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFindRequest.ProtoReflect.Descriptor instead.
func (*OrderFindRequest) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{4}
}

type OrderFindResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: json:"code" form:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//@inject_tag: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" form:"msg"`
	//@inject_tag: json:"data"
	Data *OrderItem `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (x *OrderFindResponse) Reset() {
	*x = OrderFindResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFindResponse) ProtoMessage() {}

func (x *OrderFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFindResponse.ProtoReflect.Descriptor instead.
func (*OrderFindResponse) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{5}
}

func (x *OrderFindResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderFindResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderFindResponse) GetData() *OrderItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type OrderSelectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderSelectRequest) Reset() {
	*x = OrderSelectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSelectRequest) ProtoMessage() {}

func (x *OrderSelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSelectRequest.ProtoReflect.Descriptor instead.
func (*OrderSelectRequest) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{6}
}

type OrderItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{7}
}

type OrderSelectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//@inject_tag: json:"code" form:"code"
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code" form:"code"`
	//@inject_tag: json:"msg" form:"msg"
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg" form:"msg"`
	//@inject_tag: json:"data"
	Data []*OrderItem `protobuf:"bytes,3,rep,name=data,proto3" json:"data"`
}

func (x *OrderSelectResponse) Reset() {
	*x = OrderSelectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_OrderHandler_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSelectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSelectResponse) ProtoMessage() {}

func (x *OrderSelectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_OrderHandler_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSelectResponse.ProtoReflect.Descriptor instead.
func (*OrderSelectResponse) Descriptor() ([]byte, []int) {
	return file_OrderHandler_proto_rawDescGZIP(), []int{8}
}

func (x *OrderSelectResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OrderSelectResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *OrderSelectResponse) GetData() []*OrderItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_OrderHandler_proto protoreflect.FileDescriptor

var file_OrderHandler_proto_rawDesc = []byte{
	0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x15, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x3c, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x15, 0x0a,
	0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x14, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d,
	0x73, 0x67, 0x22, 0x12, 0x0a, 0x10, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5c, 0x0a, 0x11, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46,
	0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x14, 0x0a, 0x12, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x22, 0x5e, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65,
	0x6d, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x82, 0x02, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x04, 0x46, 0x69, 0x6e, 0x64,
	0x12, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x69, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x46, 0x69, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3b, 0x0a, 0x06, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x62, 0x2e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x65, 0x6c, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_OrderHandler_proto_rawDescOnce sync.Once
	file_OrderHandler_proto_rawDescData = file_OrderHandler_proto_rawDesc
)

func file_OrderHandler_proto_rawDescGZIP() []byte {
	file_OrderHandler_proto_rawDescOnce.Do(func() {
		file_OrderHandler_proto_rawDescData = protoimpl.X.CompressGZIP(file_OrderHandler_proto_rawDescData)
	})
	return file_OrderHandler_proto_rawDescData
}

var file_OrderHandler_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_OrderHandler_proto_goTypes = []interface{}{
	(*OrderCreatedRequest)(nil),  // 0: pb.OrderCreatedRequest
	(*OrderCreatedResponse)(nil), // 1: pb.OrderCreatedResponse
	(*OrderUpdatedRequest)(nil),  // 2: pb.OrderUpdatedRequest
	(*OrderUpdatedResponse)(nil), // 3: pb.OrderUpdatedResponse
	(*OrderFindRequest)(nil),     // 4: pb.OrderFindRequest
	(*OrderFindResponse)(nil),    // 5: pb.OrderFindResponse
	(*OrderSelectRequest)(nil),   // 6: pb.OrderSelectRequest
	(*OrderItem)(nil),            // 7: pb.OrderItem
	(*OrderSelectResponse)(nil),  // 8: pb.OrderSelectResponse
}
var file_OrderHandler_proto_depIdxs = []int32{
	7, // 0: pb.OrderFindResponse.data:type_name -> pb.OrderItem
	7, // 1: pb.OrderSelectResponse.data:type_name -> pb.OrderItem
	0, // 2: pb.OrderService.Created:input_type -> pb.OrderCreatedRequest
	2, // 3: pb.OrderService.Updated:input_type -> pb.OrderUpdatedRequest
	4, // 4: pb.OrderService.Find:input_type -> pb.OrderFindRequest
	6, // 5: pb.OrderService.Select:input_type -> pb.OrderSelectRequest
	1, // 6: pb.OrderService.Created:output_type -> pb.OrderCreatedResponse
	3, // 7: pb.OrderService.Updated:output_type -> pb.OrderUpdatedResponse
	5, // 8: pb.OrderService.Find:output_type -> pb.OrderFindResponse
	8, // 9: pb.OrderService.Select:output_type -> pb.OrderSelectResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_OrderHandler_proto_init() }
func file_OrderHandler_proto_init() {
	if File_OrderHandler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_OrderHandler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreatedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdatedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderUpdatedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFindRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderFindResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSelectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_OrderHandler_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSelectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_OrderHandler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_OrderHandler_proto_goTypes,
		DependencyIndexes: file_OrderHandler_proto_depIdxs,
		MessageInfos:      file_OrderHandler_proto_msgTypes,
	}.Build()
	File_OrderHandler_proto = out.File
	file_OrderHandler_proto_rawDesc = nil
	file_OrderHandler_proto_goTypes = nil
	file_OrderHandler_proto_depIdxs = nil
}
